export default [
	"colors.enabled",
	"colors.highlights",
	"colors.nextChapter",
	"colors.higherChapter",
	"colors.lowerChapter",
	"colors.openedChapter",
	"notifications.enabled",
	"notifications.displaySyncStart",
	"notifications.displayProgressUpdated",
	"notifications.errorNotifications",
	"notifications.errorDuration",
	"notifications.infoDuration",
	"notifications.successDuration",
	"lists.hideHigher",
	"lists.hideLower",
	"lists.hideLast",
	"reading.saveOpenedChapters",
	"reading.chaptersSaved",
	"reading.saveOnlyHigher",
	"reading.saveOnlyNext",
	"reading.confirmChapter",
	"reading.updateOnlyInList",
	"reading.saveOnLastPage",
] as MutableOption[];
